"""
Copyright start
MIT License
Copyright (c) 2024 Fortinet Inc
Copyright end
"""

# FSR Autogenerated Content. DO NOT DELETE
from .get_arcanna_response import get_arcanna_response
from .send_feedback import send_feedback
from .get_jobs import get_jobs
from .send_to_arcanna import send_to_arcanna
from .trigger_training import trigger_training
from .get_decision_set import get_decision_set
from .export_event import export_event

supported_operations = {'get_arcanna_response': get_arcanna_response, 'send_feedback': send_feedback,
                        'get_jobs': get_jobs, 'send_to_arcanna': send_to_arcanna, 'trigger_training': trigger_training,
                        'get_decision_set': get_decision_set, 'export_event': export_event}
